# suppress inspection "UnusedProperty" for whole file

### SPRING ###
spring.profiles.active=dev

### MY HUB ###
game-dir=/app/games
media-dir=/app/media

### FILES ###
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

### SERVER ###
server.port=8080

### MONITORING ###
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
