spring:
  application:
    name: my_hub
    display-name: MyHub Suite
    version: 1.3
  profiles:
    active: "dev"
---
spring: # Outside the container
  config.activate.on-profile: "dev"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:h2:mem:ss;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
server:
  port: 8080
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.prometheus.enabled: true
  metrics:
    export.prometheus: true
    tags.application: ${spring.application.name}
pl.magzik.my_hub:
  content:
    game-directory: ./tmp/games/
    media-directory: ./tmp/media/
logging:
  level:
    root: INFO
    org.springframework: INFO
    pl.magzik.my_hub: DEBUG
---
spring: # Inside the container
  config.activate.on-profile: "prod"
  servlet:
    multipart:
      max-file-size: ${MYHUB_MAX_FILE_SIZE}
      max-request-size: ${MYHUB_MAX_FILE_SIZE}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.prometheus.enabled: true
  metrics:
    export.prometheus: true
    tags.application: ${spring.application.name}
pl.magzik.my_hub:
  content:
    game-directory: /app/games/
    media-directory: /app/media/
logging:
  level:
    root: WARN
    org.springframework: WARN
    pl.magzik.my_hub: INFO