spring:
  application:
    name: my_hub
    display-name: MyHub Suite
    version: 1.3
  profiles:
    active: "dev"
---
spring:
  config.activate.on-profile: "dev"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:h2:mem:ss;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
server:
  port: 8080
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.prometheus.enabled: true
  metrics:
    export.prometheus: true
    tags.application: ${spring.application.name}
pl.magzik.my_hub:
  content:
    game-directory: ./tmp/games
    media-directory: ./tmp/media
game-dir: ./tmp/games # DEPRECATED todo;
media-dir: ./tmp/media # DEPRECATED todo;
---
spring: # Kinda redundant, but for future use ;todo;
  config.activate.on-profile: "prod"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
server:
  port: 8080
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.prometheus.enabled: true
  metrics:
    export.prometheus: true
    tags.application: ${spring.application.name}
game-dir: /app/games
media-dir: /app/media